### ISSUE TITLE
Normalize data before processing

### ISSUE THREAD

**Issue by panoti** [elrumordelaluz/element-to-path#1]
Hi,

I think we should normalize string (eg: remove redundant space) before converting to path. As we can see `polygon` below, the points string

```
<polygon style="fill:#FFB800;" points="255.395,44.756 265.842,15.28 271.066,45.875 303.153,52.591 273.678,58.934       276.787,93.882 260.37,67.515 235.496,91.892 248.306,58.188 217.089,44.631     "/>
```

was converted to

```
<path style="fill:#FFB800;"
            d="M255.395 44.756 L265.842 15.28 L271.066 45.875 L303.153 52.591 L273.678 58.934 L  L  L  L276.787 93.882 L260.37 67.515 L235.496 91.892 L248.306 58.188 L217.089 44.631 Z" />
```

So many `L` command without points data, I suggest removing the space before splitting the string at **line 61** (function `poly`)

**Comment by elrumordelaluz** [comment]
Thanks @panoti for pointing this out. Should be solved in `v1.2.1`.
