### ISSUE TITLE
Related libs and docs

### ISSUE THREAD

**Issue by lucas-janon** [elrumordelaluz/element-to-path#7]
Hi Lionel! We did a call like 2 years ago :) when I was starting to work with SVGs.

The team at designstripe is currently trying to replace a hack of using Figma to convert non-path SVG elements to paths (like this library does), so I'm curious of where you took inspiration from to build it (or if it was just by reading the SVG spec), and if there is other existing implementations in javascript or other languages, would be great to have as many sources of information as possible before building a custom solution.

Thanks!

**Comment by elrumordelaluz** [comment]
Hi Lucas,
Nice to see you again! 
Honestly I don't remember well all the sources and inputs I used at the time I needed this lib, however yes, the starting point was the spec. There are a lot of great libraries where to keep an eye, at least to helper functions or some logic used to solve svg stuff. I remember @Pomax has great ones, also @TrySound is doing a super great work at svgo moving forward.
I am sorry that I didn't documented all the libs, but it would be interesting to make it now however. In case you find more inputs, don't hesitate to use this _issue_ as a placeholder to fill with links and other info. 
Happy to contribute and talk about svg!

**Comment by Pomax** [comment]
The SVG spec for the path element's `d` property is pretty small in terms of types, so it's actually a pretty good place to start, it mostly comes down to breaking down your non-SVG paths into moves, lines, elliptical arcs, quadratic beziers, and cubic beziers. As long as you have a data structure that can capture those, with SVG serialization for each, you're halfway there =)

**Comment by lucas-janon** [comment]
The team will probably take most of the inspiration from this lib and will take a look on the spec and the mentioned libraries.
I'll ask them to send a PR if they happen to add any functionality that's not specific to designstripe and can be helpful.

Thank you @elrumordelaluz, @Pomax! 🙂
